### PR TITLE
Added tooltip colors to palette

### PR DESCRIPTION
**Pull request by tsujan**
Related to https://github.com/lxqt/lxqt-config/issues/1030

Another PR will be made for the GUI after this one is approved and merged.

### CODE REVIEW

**Comment by tsujan** [comment]
@stefonarch 
Apps that are currently running should be restarted; you could log out and in instead.

For now, please test it by using Fusion and adding `tooltip_base_color` and `tooltip_text_color` to the `Palette` section of `~/.config/lxqt/lxqt.conf`. If it isn't applied on the fly, restart the app to see the changes (and tell me).

**Review by palinek — APPROVED** [review]
Straightforward.

**Comment by stefonarch** [comment]
immagine

**Review by stefonarch — APPROVED** [review]
Works fine.

**Pull request merged**
