### PR TITLE
Fix include for libdbusmenu-qt, add support for flatpak, fix working on some DEs, add support for working without context menu, add support for Qt <5.10

### PR DESCRIPTION
**Pull request by ilya-fedin**
This PR:
* fixes the libdbusmenu-qt include line to match the pkg-config file
* makes the SNI implementation compatible with flatpak
* makes the SNI implementation compatible with some DE that checking a category of the icon
* adds support for working without context menu
* adds support for building with Qt <5.10 (e.g. in snapcraft)

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Added the Category field for comptibility with some DEs

**Comment by mymedia2** [comment]
Please split your modifications into series of isolated and independent commits. It is unclear at this point what issue solves each change.

> ... comptibility with some DEs

I discovered that the category property fixes icons in KDE Plasma 5. What other DEs did you mean?

**Comment by ilya-fedin** [comment]
> What other DEs did you mean?

Cinnamon and maybe some others that I not tested

**Comment by luis-pereira** [comment]
Will review tomorrow. Now I must go to sleep.

**Comment by ilya-fedin** [comment]
> * Commit [f5e1450](https://github.com/lxqt/lxqt-qtplugin/commit/f5e14502f495bc9d36926a90c339f2718040e840) needs `set(QT_MINIMUM_VERSION "5.7.1")` added to the `CMakeLists.txt`, otherwise the change is meaningful. Qt

fixed

**Comment by luis-pereira** [comment]
@ilya-fedin 
commit 74b869accd73bd6eac5985b523d0e9ad050fa332 is technically correct. The message should be more detailed.
I need commit https://github.com/lxqt/lxqt-qtplugin/pull/52/commits/713641b5fe1cdd12c851861b4f75cde35d1f2ba0: How does that support flatpak ? I'm confused.

**Comment by ilya-fedin** [comment]
> How does that support flatpak ?

Added explanations to the description of the commit.

**Comment by luis-pereira** [comment]
@ilya-fedin Thanks.
Changed the title to something more terse.

**Pull request merged**
