### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
Had conflicts with the master branch.

**Comment by luis-pereira** [comment]
Wasn't aware of changes in the master.
Why do we need CMake 3.18 instead of 3.16 ?

**Comment by tsujan** [comment]
3.18 is old enough: https://github.com/lxqt/lxqt/discussions/2461#discussioncomment-8631068

**Review by tsujan — APPROVED** [review]
GTM

**Pull request merged**
