### PR TITLE
Bump minimum required Qt version to 5.15

### PR DESCRIPTION
**Pull request by luis-pereira**
Part of https://github.com/lxqt/lxqt/discussions/1974.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
It isn't important but wasn't `Q_DECL_OVERRIDE` (instead of `override`) for old times?

**Comment by luis-pereira** [comment]
> It isn't important but wasn't `Q_DECL_OVERRIDE` (instead of `override`) for old times?

@tsujan Did not understand what you meant.

**Comment by tsujan** [comment]
`Q_DECL_OVERRIDE` is equal to C++11's `override`. As far as I know, Qt added it when C++11 was optional (= "old times"): If a project was built with C++11 options, it did the job of `override`; if not, it had no effect.

**Comment by tsujan** [comment]
In short, I meant changing it to `override` in new codes.

**Comment by luis-pereira** [comment]
I'm not a fan of doing only one thing in a commit. 
Yes, `override` should be used, of course.

**Pull request merged**
