### PR TITLE
Started Qt6 port

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by tsujan** [comment]
Rebasing done for 1.1.0.

**Comment by tsimonq2** [comment]
While LXQt 2.0 is still a work-in-progress, a halfway solution would be ideal here. Unfortunately, Qt 6 applications are not themed at all under LXQt 1.2. If it would be possible to build for both, that would certainly be ideal.

**Comment by tsujan** [comment]
> Unfortunately, Qt 6 applications are not themed at all under LXQt 1.2

Not only Qt6 apps will be styled but also they will use Qt6 LXQt file dialog if you install all Qt6 branches (except for that of pcmanfm-qt).

@yan12125 has provided PKGBUILDs for Arch (for example, https://aur.archlinux.org/packages/lxqt-qt6plugin-git). It should be doable for any distro that has a recent version of Qt.

**Comment by tsujan** [comment]
Any objection to merging? https://github.com/lxqt/lxqt-qtplugin/issues/78 could be addressed more consistently after merging it.

**Pull request merged**
